### PR TITLE
MVP

### PR DESCRIPTION
**Pull request by edu-stx**

### CODE REVIEW

**Comment by markmhx** [comment]
A couple nitpicks re: the pool address field:

1. You may not want to show the value in the right-hand preview area until a "full" address is entered, because partial ones show up a bit funky (notice "foo...foo" when I enter just "foo"
2. Best to turn off autocomplete, spellcheck, etc for the field to prevent the dropdown menu, etc?

Screenshot 2023-01-30 at 14 43 03

**Comment by markmhx** [comment]
Might it be best to preselect "Indefinite" for the user and placing it as the first option? If we assume most users don't want the mental overhead of setting limited.

Screenshot 2023-01-30 at 14 46 48

**Comment by markmhx** [comment]
Perhaps best to link to the contract here on the Explorer?

image

**Comment by markmhx** [comment]
Let's use `cursor: pointer` when hovering over either of these two options:

image

**Comment by kyranjamie** [comment]
Recommend replacing ttf font files for woff2

**Comment by edu-stx** [comment]
Will merge and open issues for suggestions from comments,

- https://github.com/hirosystems/stacking/issues/12
- https://github.com/hirosystems/stacking/issues/13
- https://github.com/hirosystems/stacking/issues/14
- https://github.com/hirosystems/stacking/issues/15

@kyranjamie now using woff2 fonts again

**Pull request merged**
